### ISSUE TITLE
Allow newlines & linefeeds in spreadsheet input

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/modsulator-app-rails#272]
The Martin Wong collection (among others) requires that literal newline (`\n`) and linefeed (`\r`) characters in spreadsheets are not stripped out, which is the current behavior. One or both of these lines of code may be implicated, and there may in fact be others:

* https://github.com/sul-dlss/modsulator-app-rails/blob/main/app/models/modsulator_sheet.rb#L31
* https://github.com/sul-dlss/modsulator-app-rails/blob/main/app/lib/modsulator.rb#L104

Note that this Martin Wong use case only requires that this change be made within note and abstract fields, but @arcadiafalcone has said that this may be desirable elsewhere, so if it's easier to allow this change across the entire spreadsheet, this too may be acceptable.

To make testing easier, we've already created a CSV that is a subset of actual Martin Wong data:

[Martin_Wong_sample.csv](https://github.com/sul-dlss/modsulator-app-rails/files/8826081/Martin_Wong_sample.csv)

You can test that here: https://argo-stage.stanford.edu/apos/druid:bc036dg9936/bulk_jobs (choose `Spreadsheet input; load into objects` after selecting said CSV file.)

Here is the test object in Argo: https://argo-stage.stanford.edu/view/druid:hb400xn4539
And here's its PURL page to ensure newlines (before `Painting is Forbidden` in the exhibition history note) are present: https://sul-purl-stage.stanford.edu/hb400xn4539

In addition to PURL, we should also ensure that the newlines and linefeeds make it through to SearchWorks and Exhibits (both on the item show page and in the "More details" view). If you need to consult the Access team for help with either or both of these, they will have time for this between 6/6 and 6/24.

Connects to sul-dlss/mods_display#78

**Comment by jcoyne** [comment]
@mjgiarlo @arcadiafalcone @andrewjbtw  We currently have tests for modsulator that shows encoded html gets injected into the abstract if there is formatting present.  https://github.com/sul-dlss/modsulator-app-rails/blob/e42784a5ef8343ff9d777558fcc6dea342217c05/spec/fixtures/crowdsourcing_bridget_1.xml#L26 Do we want to preserve that behavior?  If so, its hard to align modsulator with the agreement we just made with the access team about how to send italics and newlines.

**Comment by arcadiafalcone** [comment]
@jcoyne @mjgiarlo This is an old fixture and does not reflect the record's current state in production. It's OK to ignore this previous behavior and move forward as planned.

**Comment by mjgiarlo** [comment]
We decided not to go the modsulator route for this feature. Closing.
