### ISSUE TITLE
Template: add second abstract and tableOfContents fields for alternative language attributes

### ISSUE THREAD

**Issue by cebraj** [sul-dlss/modsulator-app-rails#96]
Currently, the template supports one abstract field:
`<abstract displayLabel="[[ab:displayLabel]]" lang="[[ab:language]]" script="[[ab:script]]" transliteration="[[ab:transliteration]]">[[ab:abstract]]</abstract>`

To support abstracts that have been translated into a second language, the template needs to be updated to include:
`<abstract displayLabel="[[ab1:displayLabel]]" lang="[[ab1:language]]" script="[[ab1:script]]" transliteration="[[ab1:transliteration]]" altRepGroup="[[ab1:altRepGroup]]">[[ab1:abstract]]</abstract>
<abstract displayLabel="[[ab2:displayLabel]]" lang="[[ab2:language]]" script="[[ab2:script]]" transliteration="[[ab2:transliteration]]" altRepGroup="[[ab2:altRepGroup]]">[[ab2:abstract]]</abstract>`

**Comment by arcadiafalcone** [comment]
Closed by #159
